name: Lint Checks

on:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js for linters
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install HTML, CSS, JS linters
      - name: Install linters
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard eslint

      # Lint HTML
      - name: Lint HTML
        run: |
          htmlhint "**/*.html" || true

      # Lint CSS
      - name: Lint CSS
        run: |
          stylelint "**/*.css" --config-basedir . --config '{"extends": "stylelint-config-standard"}' || true

      # Lint JS
      - name: Lint JavaScript
        run: |
          eslint "**/*.js" || true
